"""empty message

Revision ID: 70d7b47a3ff0
Revises: 3a394bb261ac
Create Date: 2024-11-02 18:09:24.783678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d7b47a3ff0'
down_revision: Union[str, None] = '3a394bb261ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'birthdays_notification_states', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'birthdays_notification_states', type_='unique')
    # ### end Alembic commands ###
