"""empty message

Revision ID: 3a394bb261ac
Revises: a382c8d67d55
Create Date: 2024-11-02 17:58:56.862304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a394bb261ac'
down_revision: Union[str, None] = 'a382c8d67d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthdays_notification_states',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timeshift', sa.Time(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthdays_notification_times',
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('user_state_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_state_id'], ['birthdays_notification_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthdays_notification_times')
    op.drop_table('birthdays_notification_states')
    # ### end Alembic commands ###
