"""empty message

Revision ID: be4737732ccc
Revises: e4b02bc4af03
Create Date: 2024-10-30 06:14:36.700185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4737732ccc'
down_revision: Union[str, None] = 'e4b02bc4af03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(), nullable=False))
    op.add_column('roles', sa.Column('alias', sa.String(), nullable=False))
    op.drop_constraint('roles_role_name_key', 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_column('roles', 'role_name')
    op.drop_column('roles', 'role_alias')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_alias', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint('roles_role_name_key', 'roles', ['role_name'])
    op.drop_column('roles', 'alias')
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
