"""empty message

Revision ID: f764d705e198
Revises: 513403750cd5
Create Date: 2025-06-23 22:25:47.432465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f764d705e198'
down_revision: Union[str, None] = '513403750cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('birthdays_uuid_key'), 'birthdays', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('birthdays_uuid_key'), 'birthdays', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
